# see https://docs.travis-ci.com/user/languages/cpp/
language: cpp

# For build environment setup
# see https://docs.travis-ci.com/user/reference/overview/
matrix:
  include:
    # see https://docs.travis-ci.com/user/languages/cpp/#gcc-on-linux
    - os: linux
      dist: xenial
      compiler: gcc
      env:
        - BUILD_TYPE=Release
    - os: linux
      dist: xenial
      compiler: gcc
      env:
        - BUILD_TYPE=Debug

    # see https://docs.travis-ci.com/user/languages/cpp/#clang
    - os: linux
      dist: xenial
      compiler: clang
      env:
        - BUILD_TYPE=Release
    - os: linux
      dist: xenial
      compiler: clang
      env:
        - BUILD_TYPE=Debug

    - os: osx
      osx_image: xcode10.1
      compiler: clang
      env:
        - BUILD_TYPE=Release
    - os: osx
      osx_image: xcode10.1
      compiler: clang
      env:
        - BUILD_TYPE=Debug

script:
  - cmake --version
  - cmake -H. -Bbuild
    -DCMAKE_VERBOSE_MAKEFILE=ON
    -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
    -DABSL_RUN_TESTS=ON
    -DABSL_USE_GOOGLETEST_HEAD=ON
  - cmake --build build --target all
  - CTEST_OUTPUT_ON_FAILURE=1 cmake --build build --target test
